//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleFactura
    {
        public int Id { get; set; }
        public int IdFactura { get; set; }
        public string Producto { get; set; }
        public decimal Cantidad { get; set; }
        public decimal PrecionUnidad { get; set; }
    
        public virtual Factura Factura { get; set; }
    }
}
