//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factura
    {
        public int Id { get; set; }
        public System.DateTime Fecha { get; set; }
        public int Proveedor { get; set; }
        public int Proyecto { get; set; }
        public int Actividad { get; set; }
        public int IdTipoCambio { get; set; }
        public Nullable<int> MontoDolares { get; set; }
        public int MontoColones { get; set; }
    }
}
