//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Historial_Salario_Empleado
    {
        public int Id { get; set; }
        public int Id_Empleado { get; set; }
        public decimal Salario_Anterios { get; set; }
        public decimal Salario_Nuevo { get; set; }
        public System.DateTime Fecha_Modificacion { get; set; }
    }
}
