//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Historial_Salario_Empleado
    {
        public int Id { get; set; }
        public int Id_Empleado { get; set; }
        public decimal Salario_Anterios { get; set; }
        public decimal Salario_Nuevo { get; set; }
        public System.DateTime Fecha_Modificacion { get; set; }
    
        public virtual Empleado Empleado { get; set; }
    }
}
