//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ingreso
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime Fecha { get; set; }
        public decimal MontoColones { get; set; }
        public Nullable<decimal> MontoDolares { get; set; }
        public Nullable<int> IdTipoCambio { get; set; }
        public int IdProyecto { get; set; }
    
        public virtual TipoCambio TipoCambio { get; set; }
    }
}
